# Generated by Django 5.0.4 on 2024-04-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_transaction_id', models.CharField(max_length=100)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('party_id_type', models.CharField(blank=True, max_length=50, null=True)),
                ('party_id', models.CharField(blank=True, max_length=50, null=True)),
                ('payer_message', models.TextField(blank=True, null=True)),
                ('payee_note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
