# Generated by Django 5.0.4 on 2024-04-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtnmo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='financial_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
